### ISSUE TITLE
How to close/flush/end ?

### ISSUE THREAD

**Issue by sp00x** [jvddavid/pino-rotating-file#2]
Was just testing this briefly and I notice that the scripts does not automatically close on completion, meaning there's probably some event handler or something that is left hanging, which is different from when using 'pino/file' where it terminates properly.

Is there some close() or end() or something method that needs to be called to make it terminate?

```typescript

import pino from 'pino';

const transport = pino.transport({
  targets: [
    {
      level: 'trace',
      'target': '@jvddavid/pino-rotating-file',
      options: {
        path: "logs",
        //pattern: "log-%Y-%M-%d-%H-%m-%s-%l-%N.log",
        pattern: "log-%Y-%M-%d-%N.log",
        maxSize: 1024 * 1024 * 10,
        sync: true,
        fsync: true,
        append: true,
        mkdir: true,
      }
    }, 
    // {
    //   level: 'trace',
    //   target: 'pino/file',
    //   options: {
    //     destination: 'test.log'
    //   }
    // },
    {
      level: 'debug',
      target: 'pino-pretty',
      options: {
      }
    }
  ]
});

let logger = pino.pino(transport);

logger.info("hello");

// script is kept open, does not terminate .. terminates properly with pino/file
```

**Comment by 1340145680** [comment]
Same problem, in my express program I manually restart serve will prompt me the port is occupied, after troubleshooting is due to the pino-rotating-file plugin is not properly closed, in the project compressed into a zip will also be prompted the log file is being used!

**Comment by 1340145680** [comment]
I found the problem, the reason is that SIGINT “does not emit the ‘exit’ event and pino transport cannot call the close method correctly.
[https://github.com/pinojs/pino/issues/2002#issuecomment-2225027612](https://github.com/pinojs/pino/issues/2002#issuecomment-2225027612)

**Comment by jvddavid** [comment]
Thanks for the feedback, I used the close-with-grace package to perform the stream closure.

```javascript
import closeWithGrace from 'close-with-grace'
import build from 'pino-abstract-transport'
import { RotateFileStream, type RotateFileTransportOptions } from './RotateFileStream'

export default (opts: RotateFileTransportOptions) => {
  const destination = new RotateFileStream(opts)
  closeWithGrace(() => {
    destination.end()
  })
  return build(
    source => {
      source.pipe(destination)
    },
    {
      close(err, cb) {
        destination.on('close', cb.bind(null, err))
        destination.end()
      },
      parse: 'lines',
      parseLine: line => line
    }
  )
}

```
